# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('latitud', models.DecimalField(decimal_places=2, max_digits=2)),
                ('longitud', models.DecimalField(decimal_places=2, max_digits=3)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourist_cards.Card')),
            ],
        ),
    ]
